### ISSUE TITLE
Error occured while retrieving data from ote-cr.cz.

### ISSUE THREAD

**Issue by Zakarumit** [grinco/ote_rate#8]
Hello,

I have started using this integration and thank its awesome. Unfortunately, twice it returned zero values which lead to triggers in automations based on electricity price which shouldnt happen. I am still a beginner but this is what I have found in log - the timestamp corresponds to the sensor returning zero price. It would be nice is developer could check this out:

Logger: custom_components.ote_rate.sensor
Source: custom_components/ote_rate/sensor.py:79
Integration: ote_rate ([documentation](https://github.com/grinco/ote_rate))
First occurred: 01:40:17 (1 occurrences)
Last logged: 01:40:17

Error occured while retrieving data from ote-cr.cz.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ote_rate/sensor.py", line 79, in _get_current_value
    json = response.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by grinco** [comment]
cloud have been a time out. haven't seen this consistently.
